# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7875dde7cd3da09451e625ef059075892ebc5d126f5948af80e3fda086c85a872862e1152ac45213c0ebe8b56a14c8bae6ee3e1dbb8339d1ed4118529b2a06a8

test:
  secret_key_base: 471390e3d99f63083ea9ae1553ec8f14617171e49b142a58a023f646bec7e2d5219efc845ae5427ec7b4392dcb81f365a088a0b8ef4c4b23a6f7e71cd3c5da65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
